# Generated by Django 2.1.7 on 2019-03-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='HitDieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitDieType', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('actions', models.TextField(null=True)),
                ('strScore', models.IntegerField()),
                ('strSave', models.IntegerField(null=True)),
                ('dexScore', models.IntegerField()),
                ('dexSave', models.IntegerField(null=True)),
                ('conScore', models.IntegerField()),
                ('conSave', models.IntegerField(null=True)),
                ('intScore', models.IntegerField()),
                ('intSave', models.IntegerField(null=True)),
                ('wisScore', models.IntegerField()),
                ('wisSave', models.IntegerField(null=True)),
                ('chaScore', models.IntegerField()),
                ('chaSave', models.IntegerField(null=True)),
                ('arcana', models.IntegerField(null=True)),
                ('athletics', models.IntegerField(null=True)),
                ('deception', models.IntegerField(null=True)),
                ('history', models.IntegerField(null=True)),
                ('insight', models.IntegerField(null=True)),
                ('intimidation', models.IntegerField(null=True)),
                ('investigation', models.IntegerField(null=True)),
                ('medicine', models.IntegerField(null=True)),
                ('nature', models.IntegerField(null=True)),
                ('perception', models.IntegerField(null=True)),
                ('performance', models.IntegerField(null=True)),
                ('persuasion', models.IntegerField(null=True)),
                ('religion', models.IntegerField(null=True)),
                ('stealth', models.IntegerField(null=True)),
                ('survival', models.IntegerField(null=True)),
                ('armorClass', models.IntegerField()),
                ('challengeRating', models.FloatField()),
                ('hitDieNum', models.IntegerField()),
                ('hitPoints', models.IntegerField()),
                ('passivePerception', models.IntegerField()),
                ('proficiencyBonus', models.IntegerField()),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Alignment')),
                ('hitDieType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.HitDieType')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Size'),
        ),
        migrations.AddField(
            model_name='monster',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.Subtype'),
        ),
        migrations.AddField(
            model_name='monster',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Type'),
        ),
    ]
