# Generated by Django 2.1.7 on 2019-03-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monster',
            new_name='Creature',
        ),
    ]
