# Generated by Django 2.1.7 on 2019-03-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0008_auto_20190326_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='conditionImmunities',
            field=models.ManyToManyField(through='codex.ConditionImmunitiesCreature', to='codex.ConditionImmunities'),
        ),
    ]
