# Generated by Django 2.1.7 on 2019-03-26 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0009_auto_20190326_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageImmunitiesCreature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Creature')),
            ],
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damageType', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='damageimmunitiescreature',
            name='damageImmunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.DamageType'),
        ),
        migrations.AddField(
            model_name='creature',
            name='damageImmunities',
            field=models.ManyToManyField(through='codex.DamageImmunitiesCreature', to='codex.DamageType'),
        ),
    ]
