# Generated by Django 2.1.7 on 2019-03-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0014_auto_20190327_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedCreature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Creature')),
                ('speed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Speed')),
            ],
        ),
        migrations.AddField(
            model_name='creature',
            name='speed',
            field=models.ManyToManyField(through='codex.SpeedCreature', to='codex.Speed'),
        ),
    ]
