# Generated by Django 2.2 on 2019-04-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='creatureinstance',
            name='ac',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creatureinstance',
            name='currentHitPoints',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creatureinstance',
            name='maxHitPoits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creatureinstance',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.EncounterInstance'),
        ),
    ]
