# Generated by Django 2.2 on 2019-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatureinstance',
            name='init',
            field=models.IntegerField(null=True),
        ),
    ]
