# Generated by Django 2.2 on 2019-04-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_creatureinstance_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatureinstance',
            name='color',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
